<a href="https://colab.research.google.com/github/codernikita/cognitive-computing/blob/main/cc_ass4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUE1:

In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print("normal array:")
print(arr1)
arr2=arr1+2
print("array after addition of 2:")
print(arr2)
arr3=arr1*3
print("array after multiplication with 3:")
print(arr3)
arr4=arr1/2
print("after after division by 2:")
print(arr4)


normal array:
[1 2 3 4 5]
array after addition of 2:
[3 4 5 6 7]
array after multiplication with 3:
[ 3  6  9 12 15]
after after division by 2:
[0.5 1.  1.5 2.  2.5]


QUE2:


In [7]:
arr=np.array([1,2,3,6,4,5])
rev_arr=arr[::-1]
print("reversed array:")
print(rev_arr)


reversed array:
[5 4 6 3 2 1]


In [31]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
dic1={}
for i in x:
  if i in dic1:
    dic1[i]+=1
  else:
    dic1[i]=1
print(dic1)
for i in dic1:
  if dic1[i]==max(dic1.values()):
    j=i
    print(j)
    print(f"the most occuring value is {i} and its frequecy is {dic1[i]}")
h=0
for k in x:
    if k==j:
      print(f"the index is:{h}")
    h=h+1



{1: 5, 2: 2, 3: 1, 4: 1, 5: 1}
1
the most occuring value is 1 and its frequecy is 5
the index is:0
the index is:5
the index is:7
the index is:8
the index is:9


In [33]:
x = np.array([1,1,1,2,3,4,2,4,3,3])
dic1={}
for i in x:
  if i in dic1:
    dic1[i]+=1
  else:
    dic1[i]=1
print(dic1)
for i in dic1:
  if dic1[i]==max(dic1.values()):
    j=i
    print(j)
    print(f"the most occuring value is {i} and its frequecy is {dic1[i]}")
    h=0
    for k in x:
      if k==j:
       print(f"the index is:{h}")
      h=h+1


{1: 3, 2: 2, 3: 3, 4: 2}
1
the most occuring value is 1 and its frequecy is 3
the index is:0
the index is:1
the index is:2
3
the most occuring value is 3 and its frequecy is 3
the index is:4
the index is:8
the index is:9


QUE3:

In [39]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print(f"first row and second column is:{arr[0,1]}")
print(f"third row and first column is:{arr[2,0]}")


[[10 20 30]
 [40 50 60]
 [70 80 90]]
first row and second column is:20
third row and first column is:70


In [57]:

Coder_Nikita = np.linspace(10, 100, 25)
print(Coder_Nikita)
print(f" the dimension is:{Coder_Nikita.ndim}")
print(f"the size is:{Coder_Nikita.size}")
print(f"the shape is:{Coder_Nikita.shape}")
print(f"the data type is:{Coder_Nikita.dtype}")
print(f"the item size is:{Coder_Nikita.itemsize} and total size consumed is {Coder_Nikita.itemsize*Coder_Nikita.size}")
arr_new=Coder_Nikita.reshape(25,1)
print(arr_new)
Coder_Nikita.T


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
 the dimension is:1
the size is:25
the shape is:(25,)
the data type is:float64
the item size is:8 and total size consumed is 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

QUE5:

In [69]:
ucs420_Nikita=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Nikita)
mean=np.mean(ucs420_Nikita)
print(f"the mean is:{mean}")
median=np.median(ucs420_Nikita)
print(f"the median is:{median}")
min=np.min(ucs420_Nikita)
print(f"the minimum is:{min}")
unique=np.unique(ucs420_Nikita)
print(f"the unique values are:{unique}")
reshaped_ucs420_Nikita=ucs420_Nikita.reshape(4,3)
print(f"the reshaped array is:{reshaped_ucs420_Nikita}")
resized_ucs420_Nikita=np.resize(ucs420_Nikita,(2,3))
print(f"the resized array is:{resized_ucs420_Nikita}")




[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
the mean is:43.333333333333336
the median is:37.5
the minimum is:10
the unique values are:[10 15 20 30 35 40 50 60 70 80 90]
the reshaped array is:[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
the resized array is:[[10 20 30]
 [40 50 60]]
